import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react';
export function MotionControls(){
 const [off,setOff]=useState(false);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setOff(q.matches);sync();q.addEventListener('change',sync);return()=>q.removeEventListener('change',sync)},[]);
 useEffect(()=>{document.documentElement.dataset.motion=off?'off':'on';window.dispatchEvent(new Event('gamma-motion'));return()=>{delete document.documentElement.dataset.motion}},[off]);
 useEffect(()=>{const bar=document.querySelector<HTMLElement>('.reading-progress');const hero=document.querySelector<HTMLElement>('.hero');const fine=matchMedia('(pointer:fine)');let frame=0,pointerFrame=0,max=1,visible=true,x=0,y=0;const measure=()=>{max=Math.max(1,document.documentElement.scrollHeight-innerHeight)};const paint=()=>{frame=0;bar?.style.setProperty('transform',`scaleX(${Math.min(1,scrollY/max)})`)};const scroll=()=>{if(!frame&&!document.hidden)frame=requestAnimationFrame(paint)};const resize=new ResizeObserver(()=>{measure();scroll()});resize.observe(document.body);const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(!visible)hero?.style.removeProperty('--look-x')});if(hero)observer.observe(hero);const move=(e:PointerEvent)=>{if(off||!fine.matches||!visible||document.hidden)return;x=(e.clientX/innerWidth-.5)*18;y=(e.clientY/innerHeight-.5)*12;if(!pointerFrame)pointerFrame=requestAnimationFrame(()=>{pointerFrame=0;hero?.style.setProperty('--look-x',x+'px');hero?.style.setProperty('--look-y',y+'px')})};const reset=()=>{hero?.style.setProperty('--look-x','0px');hero?.style.setProperty('--look-y','0px')};measure();paint();window.addEventListener('scroll',scroll,{passive:true});hero?.addEventListener('pointermove',move,{passive:true});hero?.addEventListener('pointerleave',reset);return()=>{cancelAnimationFrame(frame);cancelAnimationFrame(pointerFrame);resize.disconnect();observer.disconnect();window.removeEventListener('scroll',scroll);hero?.removeEventListener('pointermove',move);hero?.removeEventListener('pointerleave',reset);reset()}},[off]);
 return <><div className="reading-progress" aria-hidden="true"/><button className="motion-control" aria-pressed={off} onClick={()=>setOff(!off)} aria-label="Sade görünüm">{off?'Hareketleri aç':'Hareketleri azalt'} <span aria-hidden="true">{off?'▷':'Ⅱ'}</span></button></>
}
export default function ColorLab(){const [split,setSplit]=useState(50);const [look,setLook]=useState('cinema');const frame=useRef<HTMLDivElement>(null);const dragBounds=useRef({left:0,width:1});const drag=(e:PointerEvent<HTMLDivElement>)=>{if(e.currentTarget.hasPointerCapture(e.pointerId))setSplit(Math.round(Math.max(0,Math.min(100,(e.clientX-dragBounds.current.left)/dragBounds.current.width*100))))};return <section className="section color-lab" id="color-lab"><div className="section-heading"><div><p className="eyebrow">RENK ODASI / İNTERAKTİF DENEYİM</p><h2>Aynı kare.<br/><span>Başka bir his.</span></h2></div><p>Renk, bir hikâyenin tonunu değiştirir. Çizgiyi kaydırın; farklı görsel yorumları karşılaştırın.</p></div><div className="look-options" aria-label="Renk yorumları">{[['cinema','01 / Sinematik'],['warm','02 / Sıcak'],['mono','03 / Siyah beyaz']].map(([id,label])=><button key={id} aria-pressed={look===id} onClick={()=>setLook(id)}>{label}</button>)}</div><div ref={frame} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();dragBounds.current={left:r.left,width:r.width};e.currentTarget.setPointerCapture(e.pointerId);drag(e)}} onPointerMove={drag} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} className={'grade-frame look-'+look} style={{'--split':split+'%'} as CSSProperties}><img src="/images/aerial.webp" alt="Dağlar ve kıyı yolu üzerinde temsili hava çekimi" width="1536" height="1024" loading="lazy"/><div className="grade-overlay" aria-hidden="true"><img src="/images/aerial.webp" alt="" width="1536" height="1024" loading="lazy"/></div><span className="grade-label original">Özgün görsel</span><span className="grade-label graded">Renk yorumu</span><div className="grade-divider" aria-hidden="true"><span>↔</span></div></div><label className="grade-control">Karşılaştırmayı kaydırın<input type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))} aria-label="Renk karşılaştırma konumu" aria-valuetext={`Renk yorumu yüzde ${split}`}/><output>{split}%</output></label><div className="lab-foot"><p>Yapay zekâ ile oluşturulmuş temsili görsel üzerinde tarayıcı renk simülasyonu. Gerçek müşteri projesi veya profesyonel color grading sonucu değildir.</p><a className="text-link" href="#contact">Filminizin rengini konuşalım ↗</a></div></section>}
