import { useEffect, useRef, useState } from 'react';
const scenes=[
 {label:'GÖRÜNTÜ',title:<>Her detay.<br/><em>Bir duygu.</em></>,image:'camera-cutout.webp',name:'Blackmagic Cinema Camera 6K',copy:'Işığı, dokuyu ve hareketi aynı kadrajda buluşturuyoruz. Hikâyenin karakteri daha ilk planda ortaya çıkıyor.',spec:'SİNEMATOGRAFİ / BLACKMAGIC 6K',alt:'Blackmagic Cinema Camera 6K sinema kamerası'},
 {label:'IŞIK',title:<>Gölgeyi kur.<br/><em>Hikâyeyi aç.</em></>,image:'light.webp',name:'Işık & atmosfer',copy:'Yumuşak bir geçiş. Keskin bir silüet. Işığı yalnızca görünür kılmak için değil, sahnenin duygusunu kurmak için kullanıyoruz.',spec:'IŞIK TASARIMI / KONTROLLÜ KONTRAST',alt:'Reflektörlü profesyonel prodüksiyon ışığı'},
 {label:'SES',title:<>Görünmeyeni<br/><em>hissettir.</em></>,image:'sound.webp',name:'Ses & mekân',copy:'Bir nefes, bir adım, mekânın sesi. Görüntünün dışında kalan dünyayı, izleyicinin hikâyeye bağlandığı bir deneyime dönüştürüyoruz.',spec:'SES KAYDI / DİYALOG / ATMOSFER',alt:'Profesyonel shotgun mikrofon ve titreşim önleyici bağlantısı'},
 {label:'STABİLİTE',title:<>Hareket özgür.<br/><em>Kadraj dengeli.</em></>,image:'rs4-pro.webp',name:'DJI RS 4 Pro',copy:'Yürüyüş, takip ve mekân geçişlerinde kameranın hareketini hikâyenin ritmine bağlıyoruz. DJI RS 4 Pro ile kontrollü, akıcı bir kamera dili.',spec:'GIMBAL / DJI RS 4 PRO',alt:'Kamera takılı DJI RS 4 Pro üç eksenli gimbal stabilizatör'}
];
export default function Equipment(){
 const root=useRef<HTMLElement>(null);const [active,setActive]=useState(0);const [linear,setLinear]=useState(false);
 useEffect(()=>{
 const node=root.current;if(!node)return;const sticky=node.querySelector<HTMLElement>('.equipment-stage')!;const panels=[...node.querySelectorAll<HTMLElement>('.equipment-panel')];const query=matchMedia('(max-width: 760px), (prefers-reduced-motion: reduce)');let frame=0,last=-1,visible=false,linearMode=false,start=0,travel=1;
 const measure=()=>{linearMode=query.matches||document.documentElement.dataset.motion==='off';setLinear(linearMode);const inset=parseFloat(getComputedStyle(sticky).top)||0;start=scrollY+node.getBoundingClientRect().top-inset;travel=Math.max(1,node.offsetHeight-sticky.offsetHeight);tick()};
 const update=()=>{frame=0;if(linearMode||!visible||document.hidden)return;const p=Math.max(0,Math.min(1,(scrollY-start)/travel));node.style.setProperty('--progress',String(p));const raw=p*(scenes.length-1),base=Math.floor(raw),t=Math.max(0,Math.min(1,((raw-base)-.28)/.44));const stage=Math.min(scenes.length-1,base+t*t*(3-2*t)),next=Math.round(stage);if(next!==last){last=next;setActive(next)}panels.forEach((el,i)=>{const d=stage-i;el.style.setProperty('--distance',d.toFixed(4));const alpha=Math.max(0,1-Math.abs(d));el.style.setProperty('--alpha',String(alpha));el.style.setProperty('--copy-alpha',String(Math.max(0,Math.min(1,(alpha-.52)/.48))));el.style.setProperty('--focus-blur',alpha>.001&&alpha<.999?((1-alpha)*6).toFixed(2)+'px':'0px');el.style.visibility=Math.abs(d)>=1?'hidden':'visible'})};
 const tick=()=>{if(!frame&&visible&&!linearMode&&!document.hidden)frame=requestAnimationFrame(update)};const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;node.classList.toggle('in-view',visible);if(visible){measure();tick()}},{rootMargin:'100px'});observer.observe(node);const resize=new ResizeObserver(measure);resize.observe(node);measure();window.addEventListener('scroll',tick,{passive:true});window.addEventListener('resize',measure);window.addEventListener('gamma-motion',measure);document.addEventListener('visibilitychange',tick);query.addEventListener('change',measure);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();resize.disconnect();window.removeEventListener('scroll',tick);window.removeEventListener('resize',measure);window.removeEventListener('gamma-motion',measure);document.removeEventListener('visibilitychange',tick);query.removeEventListener('change',measure)}
 },[]);
 const jump=(i:number)=>{const el=root.current;if(!el)return;if(linear){el.querySelectorAll('.equipment-panel')[i]?.scrollIntoView({behavior:'auto'});return}const sticky=el.querySelector<HTMLElement>(".equipment-stage")!;const inset=parseFloat(getComputedStyle(sticky).top)||0;window.scrollTo({top:scrollY+el.getBoundingClientRect().top-inset+(el.offsetHeight-sticky.offsetHeight)*i/(scenes.length-1),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};
 return <section ref={root} id="production" className={'equipment'+(linear?' linear':'')} aria-label="Prodüksiyonun dört boyutu"><div className="equipment-stage"><div className="scene-haze" aria-hidden="true"/><div className="depth-foreground" aria-hidden="true"/><div className="scene-heading"><p className="eyebrow">KADRAJIN ARKASINDA</p><span className="scene-counter">0{active+1} <i>/ 0{scenes.length}</i></span></div><div className="equipment-panels">{scenes.map((s,i)=><article className={'equipment-panel scene-'+i} key={s.label} style={{'--alpha':i===0?1:0,'--distance':-i} as React.CSSProperties} aria-hidden={!linear&&active!==i}><div className="equipment-copy"><p className="scene-label">0{i+1} — {s.label}</p><h2>{s.title}</h2><p className="scene-description">{s.copy}</p><span className="scene-spec">{s.spec}</span></div><div className="equipment-visual"><div className="object-orbit" aria-hidden="true"/><img className="equipment-object" src={'/images/'+s.image} alt={s.alt} width="1200" height="1000" loading="lazy"/><span className="equipment-name">{s.name}</span></div></article>)}</div><div className="scene-footer"><div className="scene-nav">{scenes.map((s,i)=><button key={s.label} className={active===i?'active':''} onClick={()=>jump(i)} aria-current={active===i?'step':undefined}><span>0{i+1}</span>{s.label}</button>)}</div><a href="#portfolio" className="scene-skip">Vitrine geç ↓</a></div><p className="equipment-note">Işık ve ses ürünleri prodüksiyon yaklaşımını temsil eder. Ekipman seçimi projeye göre yapılır.</p></div></section>
}

