import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowLeft,ArrowRight,X} from 'lucide-react';
const phases=[
 {name:'Pre-production',subtitle:'Hikâyeyi tasarla.',intro:'İyi bir film, kamera açılmadan başlar.',image:'planning.webp',alt:'Storyboard ve çekim planıyla hazırlanan prodüksiyon masası',steps:[
  {title:'Brief & fikir',text:'Önce sizi dinliyoruz. Hedefinizi, izleyicinizi ve vermek istediğiniz mesajı netleştirerek yaratıcı yönü belirliyoruz.',image:'process-brief.webp',alt:'Yaratıcı ekibin marka hedeflerini ve görsel referansları değerlendirdiği toplantı',detail:'Hedef · İzleyici · Yaratıcı yaklaşım'},
  {title:'Senaryo & storyboard',text:'Fikri sahnelere dönüştürüyoruz. Hikâyenin akışını, kadrajları ve geçişleri çekimden önce görünür kılıyoruz.',image:'process-storyboard.webp',alt:'Yönetmenin hikâyeyi storyboard karelerine dönüştürdüğü hazırlık masası',detail:'Hikâye akışı · Kadraj · Görsel dil'},
  {title:'Mekân & ekip',text:'Hikâyeye uygun mekânı, çekim ekibini ve ihtiyaç duyulan ekipmanı birlikte planlıyoruz.',image:'process-location.webp',alt:'Çekim ekibinin mekânın ışığını ve kadraj olanaklarını değerlendirdiği keşif',detail:'Keşif · Ekip · Teknik ihtiyaçlar'},
  {title:'Çekim planı',text:'Sahneleri, zamanlamayı ve hazırlıkları tek bir planda topluyoruz. Set günü herkes neye odaklanacağını biliyor.',image:'process-schedule.webp',alt:'Yapım sorumlusunun sahneleri ve çekim zamanlamasını planladığı çalışma masası',detail:'Çekim listesi · Takvim · Hazırlık'}]},
 {name:'Production',subtitle:'Hikâyeyi yaşat.',intro:'Planı ışığa, sese ve harekete dönüştürüyoruz.',image:'process-production-cover.webp',alt:'Kamera, ışık ve çekim ekibinin birlikte çalıştığı sinema seti',steps:[
  {title:'Kamera & kadraj',text:'Hikâyenin duygusuna uygun lens, açı ve kompozisyonu seçiyoruz. Her plan anlatmak istediğimiz fikre hizmet ediyor.',image:'process-camera.webp',alt:'Sette kameramanın oyuncuya göre kadrajı ayarlaması',detail:'Kompozisyon · Lens · Görüntü'},
  {title:'Işık & atmosfer',text:'Işığın yönü, rengi ve gölgesiyle sahnenin karakterini kuruyoruz. Görsel bütünlüğü çekim boyunca koruyoruz.',image:'process-lighting.webp',alt:'Işık ekibinin sahnedeki kişiyi softbox ile aydınlatması',detail:'Işık tasarımı · Kontrast · Atmosfer'},
  {title:'Ses & performans',text:'Diyalogları ve ortam sesini özenle kaydediyoruz. Kamera önündeki anlatımın doğal ve güçlü olmasına odaklanıyoruz.',image:'process-sound-recording.webp',alt:'Çekim sırasında diyalog kaydeden boom operatörü ve ses ekibi',detail:'Diyalog · Ortam sesi · Yönlendirme'},
  {title:'Hareket & takip',text:'Gimbal ve projeye uygun hava çekimleriyle bakış açısını genişletiyoruz. Hareketin hızını hikâyenin ritmi belirliyor.',image:'process-tracking.webp',alt:'Hareket eden kişiyi kamera ve gimbal ile takip eden operatör',detail:'DJI RS 4 Pro · Takip · Akıcı planlar'}]},
 {name:'Post-production',subtitle:'Hikâyeyi tamamla.',intro:'Görüntüler birleşir. Filmin duygusu ortaya çıkar.',image:'editing.webp',alt:'Kurgu ekranları ve renk düzenleme konsolu bulunan stüdyo',steps:[
  {title:'Seçim & kurgu',text:'En güçlü anları seçiyor, filmin akışını kuruyoruz. Planların süresi ve geçişler, hikâyenin temposunu şekillendiriyor.',image:'process-edit.webp',alt:'Kurgu odasında çekimleri zaman çizelgesinde birleştiren editör',detail:'Plan seçimi · Akış · Ritim'},
  {title:'Renk & görsel bütünlük',text:'Planlar arasında renk ve ışık dengesini kuruyoruz. Filmin karakterine uygun tonlarla atmosferi tamamlıyoruz.',image:'process-color.webp',alt:'Renk uzmanının konsol ve referans ekranıyla görüntü tonlarını düzenlemesi',detail:'Renk dengesi · Color grading · Doku'},
  {title:'Ses tasarımı & miks',text:'Diyalog, müzik ve efektleri dengeliyoruz. Görünmeyen detaylarla izleyicinin filmle kurduğu bağı güçlendiriyoruz.',image:'process-sound-mix.webp',alt:'Ses stüdyosunda film sesini miksleyen ses tasarımcısı',detail:'Müzik · Efekt · Ses dengesi'},
  {title:'Son kontrol & teslim',text:'Görüntü ve sesi birlikte kontrol ediyoruz. Filmi yayınlanacağı mecraya uygun oran, çözünürlük ve formatta hazırlıyoruz.',image:'process-delivery.webp',alt:'Filmin bilgisayar ve mobil ekranlarda yayın öncesi kontrolü',detail:'Kontrol · Format · Yayına hazırlık'}]}
];
export default function ProcessGallery(){
 const [selected,setSelected]=useState<number|null>(null),[step,setStep]=useState(0);const modal=useRef<HTMLDialogElement>(null),rail=useRef<HTMLDivElement>(null),opener=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{if(selected===null)return;const d=modal.current!;d.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;opener.current?.focus()}},[selected]);
 const close=()=>{modal.current?.close();setSelected(null)};
 const move=(index:number)=>{const r=rail.current;if(!r)return;const target=r.children[index] as HTMLElement;if(target)r.scrollTo({left:target.offsetLeft,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.motion==='off'?'auto':'smooth'})};
 const current=selected===null?null:phases[selected];
 return <section id="portfolio" className="section process-section"><div className="section-heading"><div><p className="eyebrow">01 / GÖRSEL DÜNYAMIZ</p><h2>Fikirden filme.<br/><span>Her aşamada birlikte.</span></h2></div><p>Üç bölüm. Tek bir yaratıcı bakış.<br/>Bir başlık seçin, yapım sürecimizi keşfedin.</p></div><div className="process-grid">{phases.map((phase,i)=><button className="process-card" key={phase.name} onClick={e=>{opener.current=e.currentTarget;setStep(0);setSelected(i)}} aria-haspopup="dialog"><img src={'/images/'+phase.image} alt={phase.alt} width="1200" height="800" loading="lazy"/><span className="process-card-shade"/><span className="process-number">0{i+1} / YAPIM SÜRECİ</span><span className="process-glass"><span className="process-title">{phase.name}</span><strong>{phase.subtitle}</strong><span className="process-open">4 aşamayı keşfet <ArrowUpRight size={20}/></span></span></button>)}</div><p className="sample-note">Görseller yapım aşamalarını anlatmak için yapay zekâ ile oluşturulmuştur; gerçek ekip veya müşteri projelerini göstermez.</p>
 <dialog ref={modal} className="process-dialog" aria-labelledby="process-dialog-title" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===modal.current)close()}}>{current&&<><div className="process-dialog-head"><div><p className="eyebrow">YAPIM SÜRECİ / 0{selected!+1}</p><h2 id="process-dialog-title">{current.name}</h2><p>{current.intro}</p></div><button autoFocus className="process-close" aria-label="Süreç penceresini kapat" onClick={close}><X size={22}/></button></div><div ref={rail} className="process-rail" tabIndex={0} aria-label="Yapım aşamaları; sağ ve sol oklarla gezin" onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(Math.max(0,Math.min(3,step+(e.key==='ArrowRight'?1:-1))))}}} onScroll={e=>{const r=e.currentTarget;const width=(r.children[0] as HTMLElement)?.offsetWidth||1;setStep(Math.max(0,Math.min(3,Math.round(r.scrollLeft/width))))}}>{current.steps.map((s,i)=><article className="process-slide" key={s.title} aria-label={(i+1)+' / 4: '+s.title}><div className="process-slide-image"><img src={'/images/'+s.image} alt={s.alt} width="1200" height="800" loading={i===0?'eager':'lazy'}/><span>0{i+1} / 04</span></div><div className="process-slide-copy"><span className="process-step-label">{current.name} / 0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><span className="process-detail">{s.detail}</span></div></article>)}</div><div className="process-controls"><div className="process-dots" aria-label="Aşama seçimi">{current.steps.map((s,i)=><button key={s.title} aria-label={s.title} aria-current={step===i?'step':undefined} onClick={()=>move(i)}><span/></button>)}</div><span className="process-status" aria-live="polite">{step+1} / 4</span><button className="process-arrow" aria-label="Önceki aşama" disabled={step===0} onClick={()=>move(step-1)}><ArrowLeft size={20}/></button><button className="process-arrow" aria-label="Sonraki aşama" disabled={step===3} onClick={()=>move(step+1)}><ArrowRight size={20}/></button></div></>}</dialog></section>
}
