import ProcessGallery from './components/ProcessGallery.tsx';
import DroneFlight from './components/DroneFlight.tsx';
import {MotionControls} from './components/ColorLab.tsx';
import Equipment from './components/Equipment.tsx';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, Plus, MessageCircle, Phone, Mail, Instagram } from 'lucide-react';
const services=[
 {title:'Reklam filmi',tag:'MARKANIZIN HİKÂYESİ',text:'Ürününüzü ve markanızı, izleyicinin aklında kalan bir hikâyeye dönüştürüyoruz. Konsept, çekim ve kurguyu aynı yaratıcı bakışla ele alıyoruz.',items:'Konsept geliştirme · Ürün filmi · Marka hikâyesi'},
 {title:'Kurumsal tanıtım filmi',tag:'İŞİNİZİ GÖRÜNÜR KILIN',text:'Şirketinizin insanlarını, üretimini ve vizyonunu sinematik bir dille anlatıyoruz. Elazığ merkezli yapım ekibimizle projenin ihtiyacına göre çekim planlıyoruz.',items:'Şirket tanıtımı · Röportaj · Kurumsal belgesel'},
 {title:'Drone çekimi',tag:'BAŞKA BİR PERSPEKTİF',text:'Mekânın ölçeğini ve coğrafyanın karakterini hava görüntüleriyle ortaya çıkarıyoruz. Çekim planını konuma, koşullara ve projenizin ihtiyacına göre oluşturuyoruz.',items:'Hava çekimi · Mekân tanıtımı · Sinematik planlar'},
 {title:'Sosyal medya videosu',tag:'KÜÇÜK EKRANDA BÜYÜK ETKİ',text:'Markanızın görsel dilini Instagram, TikTok ve YouTube için kısa, ritmik içeriklere taşıyoruz. Dikey ve yatay formatları yayınlanacak kanala göre hazırlıyoruz.',items:'Reels · Kısa video · Platforma uygun kurgu'},
 {title:'Kurgu & renk düzenleme',tag:'SON KARENİN ÖTESİ',text:'Görüntü, ses ve ritmi bir araya getiriyoruz. Kurgu ve color grading ile hikâyenin duygusunu belirginleştiriyor, filmin görsel bütünlüğünü tamamlıyoruz.',items:'Video kurgu · Color grading · Ses düzenleme'},
 {title:'Yaratıcı prodüksiyon',tag:'FİKİRDEN YAYINA',text:'Kısa film, müzik videosu, sahne arkası ve canlı yayın projelerinde yaratıcı planlamadan son teslimata kadar birlikte çalışıyoruz.',items:'Kısa film · Motion tasarım · Sahne arkası · Canlı yayın'}
];

export default function App(){
 const [menu,setMenu]=useState(false),[service,setService]=useState('Reklam filmi'),[prepared,setPrepared]=useState(false),[messageUrl,setMessageUrl]=useState('https://wa.me/905393231002');
 const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');if(query.matches)return;const items=document.querySelectorAll('.section-heading,.studio-grid,.contact-grid,.project-card');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08});items.forEach(el=>{el.classList.add('reveal');observer.observe(el)});return()=>{observer.disconnect();items.forEach(el=>el.classList.remove('reveal'))}},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 const pick=(value:string)=>{setService(value);setTimeout(()=>document.getElementById('contact')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}),0)};
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const body=`Merhaba Gamma Productions,\n\nAdım: ${d.get('name')}\nŞirket: ${d.get('company')||'Belirtilmedi'}\nE-posta: ${d.get('email')}\nHizmet: ${service}\n\nProjem: ${d.get('message')}`;const url=`https://wa.me/905393231002?text=${encodeURIComponent(body)}`;setMessageUrl(url);window.open(url,'_blank','noopener,noreferrer');setPrepared(true)}
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'prepare_project_inquiry',description:'Select a production service and open the contact form. Does not send a message.',inputSchema:{type:'object',properties:{service:{type:'string',enum:services.map(x=>x.title)}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{service:string})=>{if(!input||!services.some(x=>x.title===input.service))throw new Error('Geçersiz hizmet');setService(input.service);document.getElementById('contact')?.scrollIntoView();await new Promise(requestAnimationFrame);return{service:input.service,status:'form_ready',message_sent:false}}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[]);
 return <><MotionControls/><a className="skip" href="#main">İçeriğe geç</a><header><a className="brand" href="#home" aria-label="Gamma Productions ana sayfa"><img src="/gama%20productions%20red.png" alt="" width="50" height="40"/><span>GAMMA<small>PRODUCTIONS</small></span></a><button className="menu-toggle" aria-label="Menüyü aç/kapat" aria-controls="main-navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav id="main-navigation" className={menu?'open':''}>{[['production','Prodüksiyon'],['portfolio','Vitrin'],['services','Hizmetler'],['about','Stüdyo']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setMenu(false)}>Bir proje konuşalım <ArrowUpRight size={17}/></a></nav></header>
 <main id="main"><section id="home" className="hero"><img className="hero-image" src="/images/cinema.jpg" alt="Profesyonel video kamerası; temsili prodüksiyon görseli" width="1800" height="1200"/><div className="hero-shade"/><div className="hero-equipment" aria-hidden="true"><DroneFlight/><div className="hero-orbit"/><img className="hero-camera" src="/images/camera-cutout.webp" alt="" width="1785" height="881" fetchPriority="high"/><img className="hero-mic" src="/images/sound.webp" alt=""/><span className="hero-equipment-caption">BLACKMAGIC CINEMA CAMERA 6K<br/><b>GÖRÜNTÜ. IŞIK. SES.</b></span></div><div className="hero-content"><p className="eyebrow">ELAZIĞ MERKEZLİ YARATICI PRODÜKSİYON STÜDYOSU</p><p className="hero-kicker">GAMMA PRODUCTIONS — FILM & CREATIVE STUDIO</p><h1>GÖRÜNTÜYÜ<br/><em>HİSSET.</em></h1><p className="hero-copy">Sinemanın diliyle düşünüyor, markanız için çekiyoruz.<br/> Elazığ’da reklam filmi, sosyal medya içerikleri ve video prodüksiyon.</p><div className="hero-actions"><a className="button red" href="#production">Dünyamızı keşfedin <ArrowUpRight size={20}/></a><a className="text-link" href="#contact">Projenizi anlatın <ArrowUpRight size={19}/></a></div></div><div className="hero-bottom"><span>SİNEMATOGRAFİ · YARATICI YAPIM · POST-PRODÜKSİYON</span><a href="#portfolio">KEŞFET <ArrowDown size={15}/></a></div></section>
 <div className="ribbon" aria-hidden="true"><span>FİKİRDEN KADRAJA</span><i>✳</i><span>DUYGUDAN HİKÂYEYE</span><i>✳</i><span>GAMMA PRODUCTIONS</span><i>✳</i></div>
 <Equipment/><ProcessGallery/>
 <section className="section services" id="services"><div className="section-heading"><div><p className="eyebrow">02 / NE YAPIYORUZ?</p><h2>Vizyonunuz.<br/><span>Bizim kadrajımız.</span></h2></div><p>Elazığ’da reklam filmi ve video prodüksiyon.<br/>Fikir, kamera, ışık, ses ve kurgu aynı yaratıcı ekipte.</p></div><div className="service-list">{services.map((s,i)=><details key={s.title} name="production-services"><summary><span className="number">0{i+1}</span><h3>{s.title}</h3><span className="service-tag">{s.tag}</span><Plus className="plus" size={24}/></summary><div className="service-body"><p>{s.text}</p><div><p className="service-items">{s.items}</p><button className="text-link" onClick={()=>pick(s.title)}>Bu hizmeti konuşalım <ArrowUpRight size={19}/></button></div></div></details>)}</div></section>
 <section className="section studio" id="about"><p className="eyebrow">03 / STÜDYO</p><div className="studio-grid"><div><h2>Sadece görüntü değil.<br/><span>Bir bakış açısı.</span></h2><div className="studio-mark" aria-hidden="true"><img src="/gama%20productions%20red.png" alt="" loading="lazy"/><span>GAMMA<br/>PRODUCTIONS</span></div></div><div><p className="lead">Biz, hikâye anlatmayı seven bir ekibiz.</p><p>Gamma Productions, Elazığ merkezli bir yaratıcı yapım şirketi. Markaların anlatacak hikâyelerini sinematografi, kurgu ve renk ile görünür kılıyoruz. Her projede önce ne anlatmak istediğinizi dinliyor, sonra o hikâyenin görsel dilini birlikte kuruyoruz.</p><p>Blackmagic 6K çekim altyapımızla reklam, kısa film ve marka hikâyelerinde çalışıyor; ilk fikirden post-prodüksiyona kadar projenin bütününe odaklanıyoruz.</p><a className="studio-instagram" href="https://www.instagram.com/gamma_productions03/" target="_blank" rel="noopener noreferrer"><Instagram size={22}/><span>Setten kareler, son işler ve kamera arkası<strong>Instagram’da Gamma Productions ↗</strong></span></a><div className="team"><div><strong>Mehmet Fatih Aydın</strong><span>Kreatif Direktör & Sinematograf</span></div><div><strong>Sıla Turan</strong><span>Editör & İçerik Tasarımcısı</span></div><div><strong>Miraç Aydın</strong><span>Post-Prodüksiyon Sanatçısı</span></div></div></div></div></section>
 <section className="section contact" id="contact"><div className="contact-grid"><div><p className="eyebrow">04 / SIRADAKİ HİKÂYE SİZİN</p><h2>Bir fikriniz<br/>varsa, <span>başlayalım.</span></h2><p>Yeni bir marka filmi, farklı bir bakış açısı veya henüz şekillenmemiş bir fikir. Sizi dinliyoruz.</p><div className="contact-links"><a href="tel:+905393231002"><Phone size={18}/><span>+90 539 323 10 02</span><ArrowUpRight size={18}/></a><a href="mailto:info@gammaproductions.net"><Mail size={18}/><span>info@gammaproductions.net</span><ArrowUpRight size={18}/></a></div><a className="instagram-contact" href="https://www.instagram.com/gamma_productions03/" target="_blank" rel="noopener noreferrer"><Instagram size={23}/><span><strong>Instagram’dan yazın</strong><small>@gamma_productions03</small></span><ArrowUpRight size={20}/></a><p className="location">ELAZIĞ, TÜRKİYE</p></div><form ref={form} onSubmit={submit} onChange={()=>setPrepared(false)}><div className="form-row"><label>Ad soyad <span>*</span><input required name="name" autoComplete="name" placeholder="Adınız ve soyadınız" maxLength={100}/></label><label>Şirket<input name="company" autoComplete="organization" placeholder="Markanız / şirketiniz" maxLength={100}/></label></div><label>E-posta <span>*</span><input type="email" required name="email" autoComplete="email" placeholder="siz@sirketiniz.com" maxLength={150}/></label><label>Nasıl yardımcı olabiliriz?<select value={service} onChange={e=>setService(e.target.value)} name="service">{services.map(s=><option key={s.title}>{s.title}</option>)}</select></label><label>Projenizi anlatın <span>*</span><textarea required name="message" rows={4} minLength={10} maxLength={2500} placeholder="Aklınızdaki fikir, çekim yeri ve hedeflediğiniz tarih…"/></label><button type="submit" className="button red">WhatsApp’ta devam et <MessageCircle size={20}/></button><p className="form-note">Form, bilgilerinizi WhatsApp mesajına dönüştürür. Mesajı açılan pencerede siz gönderirsiniz; bu sayfada kaydedilmez.</p>{prepared&&<p role="status" className="form-status">Mesajınız hazırlandı. Açılan WhatsApp penceresinde kontrol edip gönderebilirsiniz. Pencere açılmadıysa <a href={messageUrl} target="_blank" rel="noreferrer">hazırlanan mesajı yeniden açın</a>.</p>}</form></div></section>
 </main><footer><a className="footer-word" href="#home">GAMMA<span>↗</span></a><div className="footer-bottom"><span>© 2026 Gamma Productions</span><span>Sinematografi & Video Prodüksiyon · Elazığ</span><a href="#home">Başa dön ↑</a></div></footer><a className="floating-contact" href="https://wa.me/905393231002" target="_blank" rel="noreferrer" aria-label="Gamma Productions ile WhatsApp'ta iletişime geç"><MessageCircle size={22}/><span>Bir proje konuşalım</span></a>
</>;
}



